permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Millionschen
  email: 392705120@qq.com

# 站点信息
title: Millionschen的博客 
description: Millionschen的博客
baseurl: /millionschen.github.io

# avatar头像及Favicon
avatar: http://ethanatos.qiniudn.com/magic_chicken.jpg 
favicon: http://ethanatos.qiniudn.com/magic_chicken.jpg
